CREATE TABLE IF NOT EXISTS `QURAN` (
	`ACCM_ID` INTEGER NOT NULL AUTO_INCREMENT,
        `AYAH_ID` INTEGER NOT NULL,
        `AYAH_TEXT` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
        `ORIGIN` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL, -- Makki/Madni
        `TYPE` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL, -- prayer/order/story
        `CONTEXT` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,--shaan-e-nazool
        `SURAH_ID` INTEGER NOT NULL,
        `SURAH_NAME` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
        `JUZ_ID` INTEGER NOT NULL, 
        `JUZ_NAME` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
        `REVELATION_ORDER` INTEGER NOT NULL,
	PRIMARY KEY (`ACCM_ID`) 
);

CREATE TABLE IF NOT EXISTS `QURAN_UR_MAUDUDI` (
	`ACCM_ID` INTEGER NOT NULL AUTO_INCREMENT,
        `AYAH_ID` INTEGER NOT NULL,
        `AYAH_TEXT` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
        `ORIGIN` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL, -- Makki/Madni
        `TYPE` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL, -- prayer/order/story
        `CONTEXT` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,--shaan-e-nazool
        `SURAH_ID` INTEGER NOT NULL,
        `SURAH_NAME` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
        `JUZ_ID` INTEGER NOT NULL,
        `JUZ_NAME` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,	
        `REVELATION_ORDER` INTEGER NOT NULL,
	PRIMARY KEY (`ACCM_ID`) 
);

CREATE TABLE IF NOT EXISTS `QURAN_EN_YOUSUFALI` (
	`ACCM_ID` INTEGER NOT NULL AUTO_INCREMENT,
        `AYAH_ID` INTEGER NOT NULL,
        `AYAH_TEXT` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
        `ORIGIN` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL, -- Makki/Madni
        `TYPE` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL, -- prayer/order/story
        `CONTEXT` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,--shaan-e-nazool
        `SURAH_ID` INTEGER NOT NULL,
        `SURAH_NAME` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
        `JUZ_ID` INTEGER NOT NULL,
        `JUZ_NAME` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,	
        `REVELATION_ORDER` INTEGER NOT NULL,
	PRIMARY KEY (`ACCM_ID`) 
);